name=input("what is your name?")
animal=input("give me an animal ")
action=input("give me an action in the past tense ")
place=input("give me a place ")
print(f"hello {name}! im going to make you a story. press enter to start and turn the page")
input ()
print(f"there once was a very cool {animal}")
input ()
print("but it had a very big problem")
input ()
print("it was hungry!")
input ()