name=input("what is your name? ")
animal=input("give me an animal ")
action=input("give me an action in present tense ")
place=input("give me a place ")
print(f"hello {name}! im going to make you a story. press enter to start and turn the page")
input ()
print(f"there once was a very cool {animal}")
input ()
print("but it had a very big problem")
input ()
print("it was hungry!")
input ()
print(f"so it decided to {action} for food")
input()
print(f"but it was so bad at {action}ing that it was robbed of everything it owned by the people who saw the {action}")
input()
print(f"sad and alone it wandered for a time until it came across the kindly old human named {name} ")
input()
print(f"{name} took the poor {animal} to there home the {place} ")
input()
print(f"at the {place} the {animal} was finally given the food it wanted and there it lived happily ever after ")
print("THE END")
print("made by antonio")